'use server'
import { redirect } from 'next/navigation'
import { db, initDb } from '@/lib/db'
import { briefingSchema } from '@/lib/validations'
import { createSession, ensureAdmin, verifyPassword, logout } from '@/lib/auth'

const fields=['project_name','responsible_name','email','whatsapp','instagram','website','city','project_type','main_goal','main_cta','cta_link','target_audience','audience_problem','desired_feeling','offer_description','benefits','included_items','price','bonus','deadline','guarantee_info','visual_style','colors','references_links','official_links','legal_notes','launch_date','priority']
export async function submitBriefing(_:any,formData:FormData){await initDb();const data=Object.fromEntries(fields.map(f=>[f,String(formData.get(f)||'').trim()]));const parsed=briefingSchema.safeParse(data);if(!parsed.success)return{ok:false,message:parsed.error.issues[0]?.message||'Revise o formulário'};await db.execute({sql:`INSERT INTO briefings(${fields.join(',')},raw_payload_json,status) VALUES(${fields.map(()=>'?').join(',')},?,'new')`,args:[...fields.map(f=>(parsed.data as any)[f]||''),JSON.stringify(parsed.data)]});return{ok:true,message:'Briefing enviado com sucesso! Em breve entraremos em contato.'}}
export async function loginAction(_:any,formData:FormData){await ensureAdmin();const email=String(formData.get('email')||'');const password=String(formData.get('password')||'');const res=await db.execute({sql:'SELECT * FROM admins WHERE email=?',args:[email]});const admin=res.rows[0] as any;if(!admin||!(await verifyPassword(password,admin.password_hash)))return{ok:false,message:'Login inválido'};await createSession({id:admin.id,email:admin.email,name:admin.name});redirect('/admin/dashboard')}
export async function logoutAction(){await logout();redirect('/admin')}
export async function updateStatus(formData:FormData){await initDb();const id=String(formData.get('id'));const status=String(formData.get('status'));const old=await db.execute({sql:'SELECT status FROM briefings WHERE id=?',args:[id]});const from=String((old.rows[0] as any)?.status||'');await db.execute({sql:`UPDATE briefings SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`,args:[status,id]});await db.execute({sql:'INSERT INTO status_history(briefing_id,from_status,to_status) VALUES(?,?,?)',args:[id,from,status]});redirect('/admin/kanban')}
export async function addNote(formData:FormData){await initDb();const id=String(formData.get('id'));const note=String(formData.get('note')||'').trim();if(note)await db.execute({sql:'INSERT INTO briefing_notes(briefing_id,note) VALUES(?,?)',args:[id,note]});redirect(`/admin/briefings/${id}`)}
