import React, { useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowRight, CalendarDays, Check, ChevronDown, Clock3, MapPin, Menu, Play, Sparkles, Star, Ticket, Users, X } from 'lucide-react'
import { motion } from 'motion/react'
import './styles.css'

const speakers = [
  ['Cátia Simionato', 'Evoluir é viver em conexão', '23 anos na espiritualidade', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=700&q=85'],
  ['Camila Sponton', 'Ciclos que se repetem e a autossabotagem', 'Mentora e terapeuta', 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=700&q=85'],
  ['Leandra Soares', 'Como despertar sua consciência', 'Canalizadora do Método A Nova Era', 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=700&q=85'],
  ['Michelle Gil', 'Eu Superior: a chave de saída da Matrix', 'Autora best-seller e psicóloga', 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=700&q=85'],
  ['Vera Von Sothen', 'Memórias de vidas passadas', '+26 anos de experiência', 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=700&q=85'],
  ['Paula Cabral', 'Reconectando com o Código da Fonte', '+10 mil pessoas treinadas', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=700&q=85'],
]
const benefits = ['Canalizações ao vivo com mentores', 'Práticas de cura e alinhamento energético', 'Vivências, meditações e sound healing', 'Networking com buscadores e terapeutas', 'Kit exclusivo, certificado e sorteios', 'Grupo de WhatsApp de ancoragem']
const faqs = [['Como funciona o congresso?', 'São dois dias presenciais com palestras, práticas, vivências energéticas, música, meditações e momentos de conexão.'], ['O ingresso é transferível?', 'Consulte a política vigente no momento da compra diretamente na página oficial da Kiwify.'], ['Onde será realizado?', 'No Centro de Convenções Blue Tree Transatlântico, em São Paulo. A próxima edição terá local e data confirmados em breve.'], ['Como recebo meu certificado?', 'O certificado é entregue conforme as regras de participação comunicadas pela organização no evento.']]

function App() {
  const [openFaq, setOpenFaq] = useState(null)
  const [menu, setMenu] = useState(false)
  return <div className="site">
    <div className="topbar">✨ A próxima expansão começa com uma decisão: estar presente.</div>
    <header className="nav"><a className="brand" href="#inicio"><span className="brand-mark">✦</span><span>CONGRESSO<br/><b>MULTIDIMENSIONAL</b></span></a><button className="menu-btn" onClick={() => setMenu(!menu)}>{menu ? <X/> : <Menu/>}</button><nav className={menu ? 'nav-links open' : 'nav-links'}><a href="#experiencia">A experiência</a><a href="#palestrantes">Palestrantes</a><a href="#ingressos">Ingressos</a><a href="#faq">FAQ</a><a className="nav-cta" href="#ingressos">Quero participar <ArrowRight size={16}/></a></nav></header>
    <main>
      <section id="inicio" className="hero"><div className="orb orb-one"/><div className="orb orb-two"/><div className="hero-content"><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="eyebrow"><Sparkles size={16}/> 4º Congresso da Expansão da Consciência</motion.div><motion.h1 initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{delay:.12}}><em>Desperte</em> a consciência<br/>que já existe em você.</motion.h1><motion.p initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.25}}>Dois dias para atravessar limites, liberar bloqueios e se conectar com uma nova frequência de vida.</motion.p><div className="hero-actions"><a className="button primary" href="#ingressos">SIM, QUERO EXPANDIR <ArrowRight size={18}/></a><a className="watch" href="#experiencia"><span><Play size={15} fill="currentColor"/></span> Conheça a experiência</a></div><div className="hero-proof"><div className="avatars"><i>✦</i><i>◈</i><i>☼</i><i>+</i></div><div><strong>+1.000 pessoas</strong><small>já viveram essa expansão</small></div></div></div><div className="hero-visual"><div className="halo"/><div className="visual-card"><span>UMA NOVA ERA<br/><b>COMEÇA<br/>DENTRO.</b></span></div><div className="visual-caption"><span className="line"/>Presencial · São Paulo</div></div></section>
      <section className="event-strip"><div><CalendarDays/><span><b>2 dias</b><small>de imersão</small></span></div><div><Clock3/><span><b>+21 horas</b><small>de conteúdo</small></span></div><div><Users/><span><b>Egrégora de luz</b><small>conexão e comunidade</small></span></div><div><Star/><span><b>Experiência única</b><small>para sua jornada</small></span></div></section>
      <section id="experiencia" className="section experience"><div className="section-heading"><div><span className="kicker">O chamado</span><h2>Você sente que existe<br/><em>mais</em> para viver?</h2></div><p>O Congresso Multidimensional é um encontro para quem está pronto para sair do automático, olhar para dentro e abrir espaço para uma realidade mais consciente.</p></div><div className="experience-grid"><div className="experience-image"><div className="image-credit">Imagem ilustrativa · expansão e presença</div><div className="quote">“Enquanto a Egrégora trabalha no campo sutil, sua vida começa a se transformar.”</div></div><div className="benefits"><span className="kicker">Ao seu alcance</span><h3>Uma imersão que movimenta<br/>corpo, mente e espírito.</h3>{benefits.map((item,i)=><div className="benefit" key={item}><span>0{i+1}</span><Check size={17}/><p>{item}</p></div>)}</div></div></section>
      <section id="palestrantes" className="section speakers-section"><div className="center-heading"><span className="kicker">Quem estará com você</span><h2>Vozes que ajudam você<br/><em>a saltar de nível.</em></h2><p>Conhecimento, experiência e diferentes caminhos para ampliar sua percepção.</p></div><div className="speaker-grid">{speakers.map((s,i)=><motion.article whileHover={{y:-8}} className="speaker" key={s[0]}><div className={'speaker-photo p'+i} style={{backgroundImage: `linear-gradient(180deg, transparent 35%, rgba(10,11,28,.72)), url(${s[3]})`}}><span>{['☼','◌','✦','◈','☽','∞'][i]}</span></div><div className="speaker-info"><span>PALESTRANTE 0{i+1}</span><h3>{s[0]}</h3><p>{s[1]}</p><small>{s[2]}</small></div></motion.article>)}</div><a className="text-link" href="#ingressos">Ver todos os palestrantes <ArrowRight size={17}/></a></section>
      <section className="quote-section"><div className="quote-symbol">“</div><blockquote>Não é sobre se tornar alguém novo.<br/><em>É sobre lembrar quem você é.</em></blockquote><span>— A Egrégora do Congresso Multidimensional</span></section>
      <section id="ingressos" className="section tickets"><div className="center-heading"><span className="kicker">Seu próximo passo</span><h2>Escolha viver essa<br/><em>experiência.</em></h2><p>Garanta seu lugar na próxima edição. As informações de data e lote serão atualizadas em breve.</p></div><div className="ticket-grid"><article className="ticket"><div className="ticket-top"><span>MASTER</span><Ticket/></div><h3>Passaporte Master</h3><p>O essencial para mergulhar na experiência completa.</p><ul><li><Check/>Acesso aos 2 dias</li><li><Check/>Coffee breaks e certificado</li><li><Check/>Grupo de ancoragem</li><li><Check/>Kit Master e sorteios</li></ul><a className="button outline" href="https://pay.kiwify.com.br/4nJPiUM">Quero o Master <ArrowRight size={17}/></a></article><article className="ticket featured"><div className="popular">EXPERIÊNCIA COMPLETA</div><div className="ticket-top"><span>VIP</span><Ticket/></div><h3>Passaporte VIP</h3><p>Mais conforto, proximidade e conexão com os palestrantes.</p><ul><li><Check/>Tudo do Passaporte Master</li><li><Check/>Almoço com palestrantes</li><li><Check/>Primeiras fileiras</li><li><Check/>Kit Premium exclusivo</li></ul><a className="button primary" href="https://pay.kiwify.com.br/bmapUg5">Quero o VIP <ArrowRight size={17}/></a></article></div></section>
      <section id="faq" className="section faq"><div className="section-heading"><div><span className="kicker">Ainda tem dúvidas?</span><h2>Feito para você<br/><em>se sentir seguro.</em></h2></div><p>Se não encontrar sua resposta, fale com a equipe pelo WhatsApp ou e-mail.</p></div><div className="faq-list">{faqs.map((f,i)=><div className={'faq-item '+(openFaq===i?'active':'')} key={f[0]}><button onClick={()=>setOpenFaq(openFaq===i?null:i)}><span>0{i+1}</span>{f[0]}<ChevronDown/></button>{openFaq===i&&<p>{f[1]}</p>}</div>)}</div></section>
    </main><footer><div className="brand"><span className="brand-mark">✦</span><span>CONGRESSO<br/><b>MULTIDIMENSIONAL</b></span></div><p>Uma experiência para lembrar que a expansão começa dentro.</p><div className="footer-right"><a aria-label="Instagram" href="https://instagram.com/congressomultidimensional">◎</a><small>© 2025 LSX Cursos e Treinamentos LTDA</small></div></footer>
  </div>
}
createRoot(document.getElementById('root')).render(<App />)
